# environment.yml
name: emotion_classifier_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9 # Pin to a specific patch version of 3.11 for stability
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1 # This pulls in the correct CUDA toolkit dependencies via Conda
  - ffmpeg=4.3 # From your conda list output
  - pip