#config.yml
data:
  dataset_name: "RAVDESS"
  data_dir: "./data/ravdess/data/"
  sample_rate: 16000

model:
  encoder_name: "hubert" #wav2vec2
  dropout: 0.2
  hidden_dim: 256
  num_classes: 8
  freeze_encoder: true #of false, all layer are froozen. If true, they are all frozen, the next line will set the layers to be unfreezed.
  unfreeze_last_n_layers: null

training:
  batch_size: 8
  epochs: 100
  lr: 0.0001
  max_lr: 0.01
  scheduler: "onecycle"
  resume: false

pretrained_weights: #if enabled, it starts the training using weights from the pretrained weights, specify the weight file
  enabled: false
  checkpoint_path: "runs/emotion_classifier_v10/Wav2Vec2_train11thlayer_HD256_1layerMLP_attn_maxlr-1e-2_Dropout0.5/checkpoint.pt"

logging:
  log_dir: "runs/emotion_classifier_v12/" #this is a unique folder for the training. when it reruns it overrides and deletes the file so update it as needed.
  run_label: "hubert_HD256_1layerMLP_attn_maxlr-0.03_Dropout0.2" #unique id give to the training. 
  track_run: true #track different models trained so that we can plot them together.
  runs_config_path: "configs/model_runs.yml" #where to store info about different experimentation
  misclassified_dir: "misclassified/"
  checkpoint_dir: "checkpoints/"
