#config.yml
data:
  dataset_name: "RAVDESS"
  data_dir: "./data/ravdess/data/"
  sample_rate: 16000

model:
  encoder_name: "wav2vec2"
  dropout: 0.3
  hidden_dim: 256
  num_classes: 8
  freeze_encoder: false
  unfreeze_last_n_layers: 1

training:
  batch_size: 8
  epochs: 100
  lr: 0.001
  max_lr: 0.003
  scheduler: "onecycle"
  resume: false

paths:
  run_name: "emotion_classifier_v2"
  checkpoint_dir: "checkpoints/"
  log_dir: "runs/"
  misclassified_dir: "misclassified/"

logging:
  log_dir: "runs/emotion_classifier_v2" #this is a unique id for the training. when it reruns it overrides.
  run_label: "Wav2Vec2-unfreez1-layer+Dropout0.3"
  track_run: true #track different models trained so that we can plot them together.
  runs_config_path: "configs/model_runs.yml"

