#config.yml
data:
  datasets:
    #- class_path: data.ravdess_dataset.RAVDESSDataset
    #  data_dir: 'data/ravdess/data'
    - class_path: data.cremad_dataset.CREMADataset
      data_dir: 'data/CREMA-D/data'
  sample_rate: 16000

model:
  encoder_name: "hubert" #wav2vec2
  dropout: 0.2
  hidden_dim: 256
  num_classes: 8
  freeze_encoder: true #if false, all layer are froozen. If true, they are all frozen, the next line will set the layers to be unfreezed.
  unfreeze_last_n_layers: null

training:
  batch_size: 8
  epochs: 50
  lr: 0.0001
  max_lr: 0.003
  scheduler: "onecycle"
  resume: false
  val_split: 0.2
  num_workers: 2

pretrained_weights: #if enabled, it starts the training using weights from the pretrained weights, specify the weight file
  enabled: true
  checkpoint_path: "runs/emotion_classifier_v14/hubert_CREMA_ravdess_HD256_1MLP_4Enc_maxlr0p03_D0p2/checkpoint.pt"

logging:
  log_dir: "runs/emotion_classifier_v15/" #this is a unique folder for the training. when it reruns it overrides and deletes the file so update it as needed.
  run_label: "hubert_CREMAONLY_HD256_1MLP_4Enc_maxlr0p03_D0p2" #unique id give to the training. 
  track_run: true #track different models trained so that we can plot them together.
  runs_config_path: "configs/model_runs.yml" #where to store info about different experimentation
  misclassified_dir: "misclassified/"
  checkpoint_dir: "checkpoints/"
