runs:
- label: Wav2Vec2-Freez+Dropout0.3
  log_dir: runs/emotion_classifier_v1
- label: Wav2Vec2_unfreeze_last_layer_HD256_Dropout0.3
  log_dir: runs/emotion_classifier_v2
- label: Wav2Vec2_unfreeze_last_layer_HD256_Dropout0.3
  log_dir: runs/emotion_classifier_v9/
- label: Wav2Vec2_HD256_finetune_trainlayer11_mean_pooling_maxlr-1e-2Dropout0.5
  log_dir: runs/emotion_classifier_v10/
- label: Wav2Vec2_train11thlayer_HD256_1layerMLP_attn_maxlr-3e-3_Dropout0.2
  log_dir: runs/emotion_classifier_v11/
- label: hubert_HD256_1layerMLP_attn_maxlr-0.03_Dropout0.2
  log_dir: runs/emotion_classifier_v12/
- label: hubert_CREMA_ravdess_HD256_1layerMLP_layer8to11_trained_attn_maxlr-0.03_Dropout0.2
  log_dir: runs/emotion_classifier_v13/
- label: hubert_CREMA_ravdess_HD256_1layerMLP_4Enc_maxlr_0.03_Dropout0.2
  log_dir: runs/emotion_classifier_v14/
- label: hubert_CREMAONLY_HD256_1MLP_4Enc_maxlr0p03_D0p2
  log_dir: runs/emotion_classifier_v15/
