runs:
- label: Wav2Vec2-Freez+Dropout0.3
  log_dir: runs/emotion_classifier_v1
- label: Wav2Vec2_unfreeze_last_layer_HD256_Dropout0.3
  log_dir: runs/emotion_classifier_v2
- label: Wav2Vec2_unfreeze_last_layer_HD256_Dropout0.3
  log_dir: runs/emotion_classifier_v3/
- label: Wav2Vec2_HD256_Dropout0.5
  log_dir: runs/emotion_classifier_v4/
- label: Wav2Vec2_HD256_no_freezeout_Dropout0.5
  log_dir: runs/emotion_classifier_v5/
- label: Wav2Vec2_HD256_no_freezeout_2_layers_Dropout0.5
  log_dir: runs/emotion_classifier_v6/
- label: Wav2Vec2_HD256_no_freezeout_5_layers_Dropout0.5
  log_dir: runs/emotion_classifier_v7/
- label: Wav2Vec2_HD256_finetune_trainlayer8_11_layers_Dropout0.5
  log_dir: runs/emotion_classifier_v9/
- label: Wav2Vec2_HD256_finetune_trainlayer11_mean_pooling_maxlr-1e-2Dropout0.5
  log_dir: runs/emotion_classifier_v10/
- label: Wav2Vec2_train11thlayer_HD256_1layerMLP_attn_maxlr-3e-3_Dropout0.2
  log_dir: runs/emotion_classifier_v11/
- label: hubert_HD256_1layerMLP_attn_maxlr-0.03_Dropout0.2
  log_dir: runs/emotion_classifier_v12/
